/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as NamesRouteImport } from './routes/names'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as GuardianRouteImport } from './routes/guardian'
import { Route as GrantRouteImport } from './routes/grant'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as FundsRouteImport } from './routes/funds'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ChooseRouteImport } from './routes/choose'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketsIndexRouteImport } from './routes/markets/index'
import { Route as MarketsSymbolRouteImport } from './routes/markets/$symbol'
import { Route as AssetsAssetIdRouteImport } from './routes/assets/$assetId'
import { Route as ApiIndexerWebhookRouteImport } from './routes/api/indexer/webhook'
import { Route as ApiGuardianStreamRouteImport } from './routes/api/guardian/stream'
import { Route as ApiComplianceVeriffRouteImport } from './routes/api/compliance/veriff'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const NamesRoute = NamesRouteImport.update({
  id: '/names',
  path: '/names',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianRoute = GuardianRouteImport.update({
  id: '/guardian',
  path: '/guardian',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantRoute = GrantRouteImport.update({
  id: '/grant',
  path: '/grant',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsRoute = FundsRouteImport.update({
  id: '/funds',
  path: '/funds',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseRoute = ChooseRouteImport.update({
  id: '/choose',
  path: '/choose',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsIndexRoute = MarketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketsRoute,
} as any)
const MarketsSymbolRoute = MarketsSymbolRouteImport.update({
  id: '/$symbol',
  path: '/$symbol',
  getParentRoute: () => MarketsRoute,
} as any)
const AssetsAssetIdRoute = AssetsAssetIdRouteImport.update({
  id: '/assets/$assetId',
  path: '/assets/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndexerWebhookRoute = ApiIndexerWebhookRouteImport.update({
  id: '/api/indexer/webhook',
  path: '/api/indexer/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGuardianStreamRoute = ApiGuardianStreamRouteImport.update({
  id: '/api/guardian/stream',
  path: '/api/guardian/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComplianceVeriffRoute = ApiComplianceVeriffRouteImport.update({
  id: '/api/compliance/veriff',
  path: '/api/compliance/veriff',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/choose': typeof ChooseRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/funds': typeof FundsRoute
  '/governance': typeof GovernanceRoute
  '/grant': typeof GrantRoute
  '/guardian': typeof GuardianRoute
  '/learn': typeof LearnRoute
  '/markets': typeof MarketsRouteWithChildren
  '/names': typeof NamesRoute
  '/passport': typeof PassportRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/technology': typeof TechnologyRoute
  '/vault': typeof VaultRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/markets/$symbol': typeof MarketsSymbolRoute
  '/markets/': typeof MarketsIndexRoute
  '/api/compliance/veriff': typeof ApiComplianceVeriffRoute
  '/api/guardian/stream': typeof ApiGuardianStreamRoute
  '/api/indexer/webhook': typeof ApiIndexerWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/choose': typeof ChooseRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/funds': typeof FundsRoute
  '/governance': typeof GovernanceRoute
  '/grant': typeof GrantRoute
  '/guardian': typeof GuardianRoute
  '/learn': typeof LearnRoute
  '/names': typeof NamesRoute
  '/passport': typeof PassportRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/technology': typeof TechnologyRoute
  '/vault': typeof VaultRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/markets/$symbol': typeof MarketsSymbolRoute
  '/markets': typeof MarketsIndexRoute
  '/api/compliance/veriff': typeof ApiComplianceVeriffRoute
  '/api/guardian/stream': typeof ApiGuardianStreamRoute
  '/api/indexer/webhook': typeof ApiIndexerWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/choose': typeof ChooseRoute
  '/create': typeof CreateRoute
  '/explore': typeof ExploreRoute
  '/funds': typeof FundsRoute
  '/governance': typeof GovernanceRoute
  '/grant': typeof GrantRoute
  '/guardian': typeof GuardianRoute
  '/learn': typeof LearnRoute
  '/markets': typeof MarketsRouteWithChildren
  '/names': typeof NamesRoute
  '/passport': typeof PassportRoute
  '/portfolio': typeof PortfolioRoute
  '/profile': typeof ProfileRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/technology': typeof TechnologyRoute
  '/vault': typeof VaultRoute
  '/assets/$assetId': typeof AssetsAssetIdRoute
  '/markets/$symbol': typeof MarketsSymbolRoute
  '/markets/': typeof MarketsIndexRoute
  '/api/compliance/veriff': typeof ApiComplianceVeriffRoute
  '/api/guardian/stream': typeof ApiGuardianStreamRoute
  '/api/indexer/webhook': typeof ApiIndexerWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/choose'
    | '/create'
    | '/explore'
    | '/funds'
    | '/governance'
    | '/grant'
    | '/guardian'
    | '/learn'
    | '/markets'
    | '/names'
    | '/passport'
    | '/portfolio'
    | '/profile'
    | '/sitemap.xml'
    | '/tasks'
    | '/team'
    | '/technology'
    | '/vault'
    | '/assets/$assetId'
    | '/markets/$symbol'
    | '/markets/'
    | '/api/compliance/veriff'
    | '/api/guardian/stream'
    | '/api/indexer/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/choose'
    | '/create'
    | '/explore'
    | '/funds'
    | '/governance'
    | '/grant'
    | '/guardian'
    | '/learn'
    | '/names'
    | '/passport'
    | '/portfolio'
    | '/profile'
    | '/sitemap.xml'
    | '/tasks'
    | '/team'
    | '/technology'
    | '/vault'
    | '/assets/$assetId'
    | '/markets/$symbol'
    | '/markets'
    | '/api/compliance/veriff'
    | '/api/guardian/stream'
    | '/api/indexer/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/choose'
    | '/create'
    | '/explore'
    | '/funds'
    | '/governance'
    | '/grant'
    | '/guardian'
    | '/learn'
    | '/markets'
    | '/names'
    | '/passport'
    | '/portfolio'
    | '/profile'
    | '/sitemap.xml'
    | '/tasks'
    | '/team'
    | '/technology'
    | '/vault'
    | '/assets/$assetId'
    | '/markets/$symbol'
    | '/markets/'
    | '/api/compliance/veriff'
    | '/api/guardian/stream'
    | '/api/indexer/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ChooseRoute: typeof ChooseRoute
  CreateRoute: typeof CreateRoute
  ExploreRoute: typeof ExploreRoute
  FundsRoute: typeof FundsRoute
  GovernanceRoute: typeof GovernanceRoute
  GrantRoute: typeof GrantRoute
  GuardianRoute: typeof GuardianRoute
  LearnRoute: typeof LearnRoute
  MarketsRoute: typeof MarketsRouteWithChildren
  NamesRoute: typeof NamesRoute
  PassportRoute: typeof PassportRoute
  PortfolioRoute: typeof PortfolioRoute
  ProfileRoute: typeof ProfileRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TasksRoute: typeof TasksRoute
  TeamRoute: typeof TeamRoute
  TechnologyRoute: typeof TechnologyRoute
  VaultRoute: typeof VaultRoute
  AssetsAssetIdRoute: typeof AssetsAssetIdRoute
  ApiComplianceVeriffRoute: typeof ApiComplianceVeriffRoute
  ApiGuardianStreamRoute: typeof ApiGuardianStreamRoute
  ApiIndexerWebhookRoute: typeof ApiIndexerWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/names': {
      id: '/names'
      path: '/names'
      fullPath: '/names'
      preLoaderRoute: typeof NamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian': {
      id: '/guardian'
      path: '/guardian'
      fullPath: '/guardian'
      preLoaderRoute: typeof GuardianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grant': {
      id: '/grant'
      path: '/grant'
      fullPath: '/grant'
      preLoaderRoute: typeof GrantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds': {
      id: '/funds'
      path: '/funds'
      fullPath: '/funds'
      preLoaderRoute: typeof FundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose': {
      id: '/choose'
      path: '/choose'
      fullPath: '/choose'
      preLoaderRoute: typeof ChooseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/': {
      id: '/markets/'
      path: '/'
      fullPath: '/markets/'
      preLoaderRoute: typeof MarketsIndexRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/markets/$symbol': {
      id: '/markets/$symbol'
      path: '/$symbol'
      fullPath: '/markets/$symbol'
      preLoaderRoute: typeof MarketsSymbolRouteImport
      parentRoute: typeof MarketsRoute
    }
    '/assets/$assetId': {
      id: '/assets/$assetId'
      path: '/assets/$assetId'
      fullPath: '/assets/$assetId'
      preLoaderRoute: typeof AssetsAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/indexer/webhook': {
      id: '/api/indexer/webhook'
      path: '/api/indexer/webhook'
      fullPath: '/api/indexer/webhook'
      preLoaderRoute: typeof ApiIndexerWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/guardian/stream': {
      id: '/api/guardian/stream'
      path: '/api/guardian/stream'
      fullPath: '/api/guardian/stream'
      preLoaderRoute: typeof ApiGuardianStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/compliance/veriff': {
      id: '/api/compliance/veriff'
      path: '/api/compliance/veriff'
      fullPath: '/api/compliance/veriff'
      preLoaderRoute: typeof ApiComplianceVeriffRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MarketsRouteChildren {
  MarketsSymbolRoute: typeof MarketsSymbolRoute
  MarketsIndexRoute: typeof MarketsIndexRoute
}

const MarketsRouteChildren: MarketsRouteChildren = {
  MarketsSymbolRoute: MarketsSymbolRoute,
  MarketsIndexRoute: MarketsIndexRoute,
}

const MarketsRouteWithChildren =
  MarketsRoute._addFileChildren(MarketsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ChooseRoute: ChooseRoute,
  CreateRoute: CreateRoute,
  ExploreRoute: ExploreRoute,
  FundsRoute: FundsRoute,
  GovernanceRoute: GovernanceRoute,
  GrantRoute: GrantRoute,
  GuardianRoute: GuardianRoute,
  LearnRoute: LearnRoute,
  MarketsRoute: MarketsRouteWithChildren,
  NamesRoute: NamesRoute,
  PassportRoute: PassportRoute,
  PortfolioRoute: PortfolioRoute,
  ProfileRoute: ProfileRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TasksRoute: TasksRoute,
  TeamRoute: TeamRoute,
  TechnologyRoute: TechnologyRoute,
  VaultRoute: VaultRoute,
  AssetsAssetIdRoute: AssetsAssetIdRoute,
  ApiComplianceVeriffRoute: ApiComplianceVeriffRoute,
  ApiGuardianStreamRoute: ApiGuardianStreamRoute,
  ApiIndexerWebhookRoute: ApiIndexerWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
